steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/rasyk-ka-nori/sticky-notes-frontend', '--build-arg', 'VITE_API_URL=https://sticky-notes-backend-oyj73tnptq-ew.a.run.app', '.']
images:
- 'gcr.io/rasyk-ka-nori/sticky-notes-frontend'
